# Generated by Django 4.2.20 on 2025-04-29 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud_app', '0003_changelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='changelog',
            name='additional_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changelog',
            name='item_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='changelog',
            name='original_item_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='crud_app.item'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
