# Generated by Django 4.2.20 on 2025-04-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_alter_changelog_options_changelog_additional_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='item_files/'),
        ),
    ]
